#!/usr/bin/env node

import { execFile } from "node:child_process";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import chalk from "chalk";
import { Command } from "commander";
import { scanUnityPath } from "./engine/fileScanner.js";
import type { GuardrailReport, GuardrailViolation } from "./engine/types.js";

const execFileAsync = promisify(execFile);
const hookStart = "# >>> unity-guard >>>";
const hookEnd = "# <<< unity-guard <<<";

function formatLocation(violation: GuardrailViolation): string {
  return `${violation.fileName}:${violation.line}`;
}

function printViolation(violation: GuardrailViolation): void {
  console.log(`  ${chalk.yellow("warning")} ${chalk.cyan(formatLocation(violation))} ${chalk.bold(violation.ruleName)}`);
  console.log(`  ${chalk.dim(violation.message)}`);
  console.log(`  ${chalk.green("Fix:")} ${violation.recommendation}`);
}

function printReport(report: GuardrailReport): void {
  if (report.violations.length === 0) return;
  console.log(`\n${chalk.bold(report.filePath)}`);
  for (const violation of report.violations) printViolation(violation);
}

async function lintPath(targetPath: string): Promise<number> {
  const scan = await scanUnityPath(targetPath);
  console.log(chalk.bold(`\nunity-guard lint ${chalk.dim(resolve(targetPath))}`));
  console.log(chalk.dim(`Scanned ${scan.filesScanned} C# file${scan.filesScanned === 1 ? "" : "s"}.`));

  for (const report of scan.reports) printReport(report);

  if (scan.totalViolations > 0) {
    console.log(`\n${chalk.yellow(`Found ${scan.totalViolations} guardrail violation${scan.totalViolations === 1 ? "" : "s"}.`)}`);
    return 1;
  }

  console.log(`\n${chalk.green("No guardrail violations found.")}`);
  return 0;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

async function gitPath(path: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync("git", ["rev-parse", "--git-path", path]);
    return resolve(process.cwd(), stdout.trim());
  } catch {
    throw new Error("init-hook must be run from inside a Git worktree.");
  }
}

async function repositoryRoot(): Promise<string> {
  const { stdout } = await execFileAsync("git", ["rev-parse", "--show-toplevel"]);
  return stdout.trim();
}

function hookBlock(cliPath: string): string {
  return `${hookStart}\n# Generated by unity-guard init-hook.\nrepo_root="$(git rev-parse --show-toplevel)" || exit 1\n${shellQuote(process.execPath)} ${shellQuote(cliPath)} lint "$repo_root"\nstatus=$?\n[ "$status" -eq 0 ] || exit "$status"\n${hookEnd}`;
}

async function installPreCommitHook(): Promise<void> {
  const hookPath = await gitPath("hooks/pre-commit");
  await repositoryRoot();
  const cliPath = fileURLToPath(import.meta.url);
  const block = hookBlock(cliPath);

  let existing = "";
  try {
    existing = await readFile(hookPath, "utf8");
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }

  const markerPattern = /# >>> unity-guard >>>[\s\S]*?# <<< unity-guard <<</;
  const next = markerPattern.test(existing)
    ? existing.replace(markerPattern, block)
    : `${existing.trimEnd()}${existing.trim() ? "\n\n" : ""}${block}\n`;

  await mkdir(resolve(hookPath, ".."), { recursive: true });
  await writeFile(hookPath, next, "utf8");
  await chmod(hookPath, 0o755);
  console.log(chalk.green(`unity-guard pre-commit hook installed: ${hookPath}`));
}

const program = new Command();
program
  .name("unity-guard")
  .description("Deterministic Unity C# guardrails for per-frame performance and Inspector API checks.")
  .version("0.1.0");

program
  .command("lint <path>")
  .description("Lint a Unity project directory or one C# file.")
  .action(async (targetPath: string) => {
    try {
      process.exitCode = await lintPath(targetPath);
    } catch (error: unknown) {
      console.error(chalk.red(`unity-guard: ${error instanceof Error ? error.message : String(error)}`));
      process.exitCode = 1;
    }
  });

program
  .command("init-hook")
  .description("Install or update this repository's pre-commit hook.")
  .action(async () => {
    try {
      await installPreCommitHook();
    } catch (error: unknown) {
      console.error(chalk.red(`unity-guard: ${error instanceof Error ? error.message : String(error)}`));
      process.exitCode = 1;
    }
  });

await program.parseAsync();
